---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-vol
spec:
  #storageClassName: "jenkins-backup"
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /data/jenkins/backup
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-node-0

# ---
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: jenkins-backup
#   namespace: jenkins
# provisioner: kubernetes.io/no-provisioner
# volumeBindingMode: WaitForFirstConsumer