jenkins:
  namespace: jenkins
  replicaCount: 1
  disableCSRFProtection: true
  plugins:
    - name: docker-plugin
      version: "1.5"
    - name: docker-workflow
      version: "572.v950f58993843"
    - name: github
      version: "1.37.0"
  env:
    - name: JENKINS_OPTS
      value: "--prefix=/maintenance/jenkins"
    - name: BACKUP_COUNT
      value: "1"
  backup:
    pvc:
      size: 5Gi
operator:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - k8s-node-0