apiVersion: qbec.io/v1alpha1
kind: App
metadata:
  name: app
spec:
  environments:
    default:
      defaultNamespace: app
      server: https://localhost:8001
    jenkins:
      defaultNamespace: app
      server: https://kubernetes.default.svc.cluster.local:443
      excludes: # additional components to exclude
      - other
  vars: {}
